version: "3.7"
services:
  db:
    image: postgres
    container_name: cardapioh_db
    ports:
        - "5432:5432"
    env_file:
        - .development
  web:
    build: .
    image: cardapioh
    container_name: cardapioh_web
    depends_on:
        - db
    volumes:
        - .:/cardapioh
    ports:
        - "8000:8000"
    env_file:
        - .development

