# Generated by Django 2.2.17 on 2020-11-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description_english',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
