# Generated by Django 2.2.17 on 2020-11-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_item_description_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='name_english',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
