# Generated by Django 2.2.17 on 2020-11-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20201124_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description_english',
            new_name='sub_description',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='name_english',
            new_name='sub_name',
        ),
        migrations.AddField(
            model_name='item',
            name='keywords',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
