# Generated by Django 2.2.17 on 2020-11-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20201125_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='position',
            field=models.SmallIntegerField(default=0),
        ),
    ]
